name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild -scheme Vexillum -destination generic/platform=iOS
    - name: Run tests
      run: swift test -v
